[WIP] Authentication front and backend
ColinKrist/OmahaZooNutrition pull request #7
Opened 2019-02-07 21:14 UTC by MitchellSlavik

2019-02-07 21:32 UTC, ColinKrist requested changes
not sure if syntax is correct on these suggestions, but I think having a specific email / password check on API side would be nice. Thinking long term here if people were to use the login for an external service having that check is good here.

2019-02-07 21:32 UTC, ColinKrist commented on zoo_api/server/boot/root.js
> +const loginFunc = (Account, Role) => (req, res) => {
it'd be nice to have messages regarding missing login info before a login request is made.
```suggestion
const loginFunc = (Account, Role) => (req, res) => {
  if(!req.body.email){
    res.status(401).json({ message: 'Email address missing. Please enter email address.', status: 401 });
  } else if(!req.body.password) {
    res.status(401).json({ message: 'Password missing. Please enter password.', status: 401 });
  } else {
  // do the rest of the account login
```

2019-02-07 21:32 UTC, ColinKrist commented on zoo_api/server/boot/root.js
> +          res.status(401).json({ message: 'Unable to get roles', status: 401 });
```suggestion
          res.status(401).json({ message: 'Unable to get role. Please contact your system administrator to assign a role to your account.', status: 401 });
```

2019-02-09 20:44 UTC, ColinKrist approved these changes

2019-02-21 02:09 UTC, MitchellSlavik commented on zoo_frontend/pages/_app.jsx
> +    this.api = new Api(c.authToken || '');
there is no 'this' in a static function

2019-02-21 02:44 UTC, merged